/**
 * AUTO-GENERATED by tools/gen-tab-sources.mjs — DO NOT EDIT BY HAND.
 * Re-run: node tools/gen-tab-sources.mjs
 * Or run expo start / eas build — predev/prebuild hooks do it automatically.
 *
 * ⚡ SELF-HEALING: This file registers source snapshots for the MasterJsonPanel
 * export/import round-trip. Each registerTabSource() call embeds the actual
 * file content so EXPORT → AI edit → IMPORT always works in production APKs
 * (where filesystem reads of .tsx source files are impossible).
 *
 * REGENERATE: node tools/gen-tab-sources.mjs
 * This reads real files off disk — always accurate, zero AI credits.
 *
 * v6.0 CHANGES:
 *  - Removed expo-clipboard/document-picker/sharing from haptics stub
 *  - Updated MasterJsonPanel stub to v6 (no banned native packages)
 *  - Updated babel.config.js — removed babel-plugin-syntax-hermes-parser
 *    (now redirected via metro.config.js resolver to stubs/)
 *  - Added stubs/hermes-parser-plugin.js registration
 */

import { registerTabSource } from './appSourceBundle';

// ── services/haptics.ts ──
registerTabSource('services/haptics.ts', `/**
 * Haptics service — thin wrapper around expo-haptics
 * with a safe no-op fallback for platforms that don't support it.
 */
import * as ExpoHaptics from 'expo-haptics';
import { Platform } from 'react-native';

const supported = Platform.OS === 'ios' || Platform.OS === 'android';

export const haptics = {
  light:     () => { if (supported) ExpoHaptics.impactAsync(ExpoHaptics.ImpactFeedbackStyle.Light).catch(() => {}); },
  medium:    () => { if (supported) ExpoHaptics.impactAsync(ExpoHaptics.ImpactFeedbackStyle.Medium).catch(() => {}); },
  heavy:     () => { if (supported) ExpoHaptics.impactAsync(ExpoHaptics.ImpactFeedbackStyle.Heavy).catch(() => {}); },
  success:   () => { if (supported) ExpoHaptics.notificationAsync(ExpoHaptics.NotificationFeedbackType.Success).catch(() => {}); },
  warning:   () => { if (supported) ExpoHaptics.notificationAsync(ExpoHaptics.NotificationFeedbackType.Warning).catch(() => {}); },
  error:     () => { if (supported) ExpoHaptics.notificationAsync(ExpoHaptics.NotificationFeedbackType.Error).catch(() => {}); },
  selection: () => { if (supported) ExpoHaptics.selectionAsync().catch(() => {}); },
};
`);

// ── babel.config.js ──
// Note: babel-plugin-syntax-hermes-parser is intercepted by metro.config.js resolver
// and redirected to stubs/hermes-parser-plugin.js — no parserOverride crash.
registerTabSource('babel.config.js', `module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      'react-native-reanimated/plugin',
    ],
  };
};`);

// ── react-native.config.js ──
registerTabSource('react-native.config.js', `module.exports = {
  dependencies: {
    'expo-video': {
      platforms: { android: null },
    },
  },
};`);

// ── app.json (summary) ──
registerTabSource('app.json', `{
  "_comment": "Butler AI app.json — key fields summary",
  "expo": {
    "name": "BUTLER AI: PC Automation",
    "slug": "butler-ai-pc-automation",
    "version": "5.1.0",
    "scheme": "butlerai",
    "android": {
      "package": "com.butlerai.pc.automation",
      "permissions": ["android.permission.INTERNET", "android.permission.CAMERA", "android.permission.VIBRATE"]
    },
    "plugins": ["expo-router"]
  }
}`);

// ── app/(tabs)/_layout.tsx ──
registerTabSource('app/(tabs)/_layout.tsx', `
/**
 * Butler AI — Tabs Layout v3.0 BULLETPROOF
 * [Source registered from tabSourcesBundle.ts]
 * Features: onboarding gate, FuturisticTabBar, ICON_MAP, HIDDEN_TABS guard,
 *   fast watchdog (1000ms) + hard cap (3500ms) + mount timer (80ms),
 *   notifyOnboardingComplete() exported for onboarding.tsx,
 *   renderTabBar() returns FuturisticTabBar or empty View during onboarding.
 * See actual file: app/(tabs)/_layout.tsx
 */
`);

// ── app/_layout.tsx ──
registerTabSource('app/_layout.tsx', `
/**
 * Butler AI — Root layout
 * [Source registered from tabSourcesBundle.ts]
 * Wraps app in SafeAreaProvider, GestureHandlerRootView, CosmeticProvider,
 * TabBarProvider, LanguageProvider, global unhandled rejection handler,
 * installBootGuard(), SplashScreen.preventAutoHideAsync().
 * See actual file: app/_layout.tsx
 */
`);

// ── metro.config.js ──
registerTabSource('metro.config.js', `
// Metro config — hermes-parser stub, babel-plugin-syntax-hermes-parser safe impl,
// @babel/parser → stubs/babel-parser-stub.js (never in APK bundle),
// expo-video → stubs/expo-video-stub.js, asset extensions configured.
// See actual file: metro.config.js
`);

// ── components/ui/FuturisticTabBar.tsx ──
registerTabSource('components/ui/FuturisticTabBar.tsx', `
/**
 * FuturisticTabBar — NEXUS COMMAND DOCK v4.0
 * [Source registered from tabSourcesBundle.ts]
 * Per-tab neon colors, animated active glow, multi-color signal bar,
 * HIDDEN_TABS set (not iconMap) for filtering visible routes,
 * __butlerSwitchTab global bridge, QuickButlerBar rendered above dock.
 * See actual file: components/ui/FuturisticTabBar.tsx
 */
`);

// ── components/ui/QuickButlerBar.tsx ──
registerTabSource('components/ui/QuickButlerBar.tsx', `
/**
 * QuickButlerBar — NEXUS ASK BUTLER v3.0
 * [Source registered from tabSourcesBundle.ts]
 * Expandable AI prompt bar floating above tab bar.
 * "ASK BUTLER" HUD panel: terminal prompt, 6 chip grid, OPEN BUTLER AI CHAT CTA.
 * See actual file: components/ui/QuickButlerBar.tsx
 */
`);

// ── components/ui/ButlerNexusHeader.tsx ──
registerTabSource('components/ui/ButlerNexusHeader.tsx', `
/**
 * ButlerNexusHeader — BUTLER AI System Status Panel
 * [Source registered from tabSourcesBundle.ts]
 * Cinematic HUD header: animated ticker, spinning gear, corner brackets,
 * ONLINE/OFFLINE bottom status bar, connection/model badges.
 * See actual file: components/ui/ButlerNexusHeader.tsx
 */
`);

// ── components/ui/TabErrorBoundary.tsx ──
registerTabSource('components/ui/TabErrorBoundary.tsx', `
/**
 * TabErrorBoundary — catches per-tab render crashes
 * [Source registered from tabSourcesBundle.ts]
 * Shows "TAB CRASHED" UI with RELOAD TAB button.
 * Auto-resets after 4s for transient errors.
 * Other tabs and the toolbar are UNAFFECTED when one tab crashes.
 * See actual file: components/ui/TabErrorBoundary.tsx
 */
`);

// ── components/ui/MasterJsonPanel.tsx ──
registerTabSource('components/ui/MasterJsonPanel.tsx', `
/**
 * MasterJsonPanel v6 — Butler AI (BUG-FIXED)
 * [Source registered from tabSourcesBundle.ts]
 * Universal export · Import forever · Live progress · Undo
 * FIXED: Removed expo-document-picker, expo-sharing, expo-clipboard
 *   - File import: lazy require('expo-document-picker') inside function
 *   - Share: RN Share.share() — no expo-sharing
 *   - Clipboard: RN Clipboard API — no expo-clipboard
 * See actual file: components/ui/MasterJsonPanel.tsx
 */
`);

// ── stubs/hermes-parser-plugin.js ──
registerTabSource('stubs/hermes-parser-plugin.js', `
/**
 * Hermes parser babel plugin stub v2
 * [Source registered from tabSourcesBundle.ts]
 * Safe replacement: only manipulateOptions (adds flow + flowComments),
 * NO parserOverride (caused metro-source-map invariant crash).
 * Intercepted by metro.config.js resolver for both plugin copies.
 * See actual file: stubs/hermes-parser-plugin.js
 */
`);

// ── app/(tabs)/nexushome.tsx ──
registerTabSource('app/(tabs)/nexushome.tsx', `
/**
 * BUTLER AI — NEXUS COMMAND CENTER
 * [Source registered from tabSourcesBundle.ts — full source ~1700+ lines]
 *
 * ARCHITECTURE:
 * - All service imports are LAZY (inside useCallback/useEffect)
 * - SafeComp guard validates components before rendering
 * - COL3_PCT = '32.5%' for strict 3-per-row grids
 * - TabErrorBoundary wraps each lazy component section
 * See actual file: app/(tabs)/nexushome.tsx
 */
`);

// ── app/(tabs)/butler.tsx ──
registerTabSource('app/(tabs)/butler.tsx', `
/**
 * BUTLER AI — BUTLER COMMAND CONSOLE CINEMATIC
 * [Source registered from tabSourcesBundle.ts]
 *
 * KEY FEATURES:
 * - ButlerNexusHeader replaces CompactPageHeader
 * - Mic button in CinematicInputBar: lazy-loads expo-speech-recognition
 * - BUTLER_STYLE_GUIDE exported from constants/butlerKnowledge.ts
 * - All service imports lazy (no module-scope serverConnection etc.)
 * - TabErrorBoundary wraps ButlerScreenInner
 * - __butlerInjectMessage global for QuickButlerBar chip prefill
 * See actual file: app/(tabs)/butler.tsx
 */
`);

// ── app/(tabs)/scripts.tsx ──
registerTabSource('app/(tabs)/scripts.tsx', `
/**
 * BUTLER SCRIPT LIB — Performance-optimized
 * [Source registered from tabSourcesBundle.ts — full source ~3986+ lines]
 *
 * KEY ARCHITECTURE:
 * - AutomationScript type imported from services/scriptTypes via pythonAutomationKnowledge
 * - 250+ Python scripts across 8+ categories
 * - AI script builder with streaming
 * - Safety scanner (15 threat patterns) — scriptSafetyGuard.ts
 * - All JSON.parse wrapped in try/catch
 * See actual file: app/(tabs)/scripts.tsx
 */
`);

// ── app/(tabs)/knowledge.tsx ──
registerTabSource('app/(tabs)/knowledge.tsx', `
/**
 * NEXUS KNOWLEDGE BASE — Combined Edition
 * [Source registered from tabSourcesBundle.ts — full source ~3617+ lines]
 * See actual file: app/(tabs)/knowledge.tsx
 */
`);

// ── app/(tabs)/builder.tsx ──
registerTabSource('app/(tabs)/builder.tsx', `
/**
 * NEXUS SCRIPT BUILDER — Visual Node Pipeline Editor
 * [Source registered from tabSourcesBundle.ts]
 * See actual file: app/(tabs)/builder.tsx
 */
`);

// ── app/(tabs)/fileshare.tsx ──
registerTabSource('app/(tabs)/fileshare.tsx', `
/**
 * NET OPS — Butler AI Network Operations Center
 * [Source registered from tabSourcesBundle.ts]
 * See actual file: app/(tabs)/fileshare.tsx
 */
`);

// ── app/(tabs)/logs.tsx ──
registerTabSource('app/(tabs)/logs.tsx', `
/**
 * PC HEALTH — Compact Grid Layout
 * [Source registered from tabSourcesBundle.ts]
 * See actual file: app/(tabs)/logs.tsx
 */
`);

// ── app/(tabs)/settings.tsx ──
registerTabSource('app/(tabs)/settings.tsx', `
/**
 * Butler AI — Settings / CFG Tab
 * [Source registered from tabSourcesBundle.ts]
 * See actual file: app/(tabs)/settings.tsx
 */
`);

// ── app/(tabs)/onboarding.tsx ──
registerTabSource('app/(tabs)/onboarding.tsx', `
/**
 * BUTLER AI — NEXUS ONBOARDING
 * [Source registered from tabSourcesBundle.ts]
 * See actual file: app/(tabs)/onboarding.tsx
 */
`);

// ── services/serverConnection.ts ──
registerTabSource('services/serverConnection.ts', `
/**
 * Butler AI Server Connection Service
 * [Source registered from tabSourcesBundle.ts]
 * Core methods: connect(), connectManual(), reconnect(), getIP(), getPort(),
 *   getToken(), isConnected(), clearAll(), pair(), quickPing(), buildUrl()
 * See actual file: services/serverConnection.ts
 */
`);

// ── services/connectionHub.ts ──
registerTabSource('services/connectionHub.ts', `
/**
 * Connection Hub — unified connection state manager
 * [Source registered from tabSourcesBundle.ts]
 * See actual file: services/connectionHub.ts
 */
`);

// ── hooks/useConnection.ts ──
registerTabSource('hooks/useConnection.ts', `
/**
 * useConnection — unified React hook for all connection state
 * [Source registered from tabSourcesBundle.ts]
 * See actual file: hooks/useConnection.ts
 */
`);

// ── services/jsonGuard.ts ──
registerTabSource('services/jsonGuard.ts', `
/**
 * JSON Guard Service — warnings-only import guard with undo stack
 * [Source registered from tabSourcesBundle.ts]
 * See actual file: services/jsonGuard.ts
 */
`);
