import React, { memo, useEffect, useMemo, useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useCosmetic } from '@/contexts/CosmeticContext';
import { BACKPACK_INVENTORY, INVENTORY_SECTION_ORDER, STYLE_PRESETS, InventorySection, InventoryItem, entitlementAllows } from '@/services/cosmeticVariantRegistry';
import { useSkin } from '@/hooks/useSkin';
import { loadInventoryNames } from '@/services/cosmeticInventoryNames';

const SECTION_LABELS: Record<InventorySection, string> = { styles: 'STYLES', headers: 'HEADERS', 'headers-non-homepage': 'NON-HOMEPAGE HEADERS', 'homepage-header': 'HOMEPAGE HEADER', toolbars: 'TOOLBARS', icons: 'ICONS', fonts: 'FONTS', buttons: 'BUTTONS', chat: 'CHAT', 'ai-chat-box': 'AI CHAT BOX', bubbles: 'BUBBLES', mascots: 'MASCOTS', graphs: 'GRAPHS', 'graph-titles': 'GRAPH TITLES', 'number-displays': 'NUMBER DISPLAYS', 'page-backgrounds': 'PAGE BACKGROUNDS', accessibility: 'ACCESSIBILITY', animations: 'ANIMATIONS', transitions: 'TRANSITIONS', 'loading-pages': 'LOADING PAGES', 'tip-bubbles': 'TIP BUBBLES', 'rotating-tips': 'ROTATING TIPS', 'script-icons': 'SCRIPT ICONS', haptics: 'HAPTICS', sounds: 'SOUNDS', shapes: 'SHAPES', media: 'MEDIA', shortcuts: 'SHORTCUTS', grid: 'GRID', builder: 'BUILD YOUR OWN' };
const ICONS: Record<InventorySection, string> = { styles: 'palette-swatch', headers: 'page-layout-header', 'headers-non-homepage': 'view-dashboard-outline', 'homepage-header': 'home-automation', toolbars: 'dock-bottom', icons: 'shape-outline', fonts: 'format-font', buttons: 'gesture-tap-button', chat: 'chat-outline', 'ai-chat-box': 'message-processing-outline', bubbles: 'message-outline', mascots: 'robot-outline', graphs: 'chart-line', 'graph-titles': 'format-title', 'number-displays': 'numeric', 'page-backgrounds': 'wallpaper', accessibility: 'human-greeting-proximity', animations: 'motion-play-outline', transitions: 'transition', 'loading-pages': 'loading', 'tip-bubbles': 'lightbulb-on-outline', 'rotating-tips': 'refresh-auto', 'script-icons': 'script-text-outline', haptics: 'vibrate', sounds: 'volume-high', shapes: 'shape-plus-outline', media: 'image-multiple-outline', shortcuts: 'link-variant', grid: 'grid', builder: 'robot-excited-outline' };

export const ButlerBackpackInventory = memo(function ButlerBackpackInventory() {
  const skin = useSkin();
  const { verifiedProductIds, reviewRewardUnlocked, startPreview, activePackId, applyPack, updateExtras } = useCosmetic();
  const [section, setSection] = useState<InventorySection>('styles');
  const [selected, setSelected] = useState<InventoryItem | null>(null);
  const [query, setQuery] = useState('');
  const [nicknames, setNicknames] = useState<Record<string, string>>({});
  useEffect(() => { let alive = true; loadInventoryNames(BACKPACK_INVENTORY.map(item => item.id)).then(value => { if (alive) setNicknames(value); }); return () => { alive = false; }; }, []);
  const items = useMemo(() => BACKPACK_INVENTORY.filter(item => item.section === section && (!query.trim() || `${item.label} ${item.description} ${nicknames[item.id] || ''}`.toLowerCase().includes(query.trim().toLowerCase()))), [section, query, nicknames]);
  const unlocked = (item: InventoryItem) => entitlementAllows(item.entitlement, verifiedProductIds, reviewRewardUnlocked);
  const applyStyle = (item: InventoryItem) => {
    const styleId = typeof item.patch?.styleId === 'string' ? item.patch.styleId : undefined;
    const preset = styleId ? STYLE_PRESETS.find(style => style.id === styleId) : undefined;
    if (!preset || !unlocked(item)) return;
    applyPack(preset.themeId);
    void updateExtras(preset.extras);
  };
  return <View style={[styles.root, { borderColor: `${skin.accent2}55`, backgroundColor: `${skin.bg}F2` }]}>
    <View style={styles.headingRow}><View style={[styles.backpackIcon, { borderColor: skin.accent2, backgroundColor: `${skin.accent2}18` }]}><MaterialCommunityIcons name="bag-personal-outline" size={21} color={skin.accent2} /></View><View style={{ flex: 1 }}><Text style={[styles.heading, { color: skin.text }]}>BUTLER BACKPACK</Text><Text style={[styles.sub, { color: skin.mid }]}>{BACKPACK_INVENTORY.length} BUILDING BLOCKS · TAP TO PREVIEW · SAVE TO APPLY</Text></View><View style={[styles.count, { borderColor: `${skin.ok}70` }]}><Text style={[styles.countText, { color: skin.ok }]}>{BACKPACK_INVENTORY.filter(unlocked).length}</Text><Text style={[styles.countLabel, { color: skin.mid }]}>READY</Text></View></View>
    <View style={[styles.search, { borderColor: `${skin.accent}70`, backgroundColor: `${skin.bg}E8` }]}><MaterialCommunityIcons name="magnify" size={19} color={skin.accent} /><TextInput value={query} onChangeText={setQuery} placeholder="Find a component, graph, effect, or nickname" placeholderTextColor={`${skin.mid}99`} style={[styles.searchInput, { color: skin.text }]} accessibilityLabel="Search Backpack inventory" autoCapitalize="none" returnKeyType="search" /><TouchableOpacity accessibilityRole="button" accessibilityLabel="Clear Backpack search" onPress={() => setQuery('')}><MaterialCommunityIcons name="close-circle-outline" size={18} color={query ? skin.warn : `${skin.mid}55`} /></TouchableOpacity></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.tabs}>{INVENTORY_SECTION_ORDER.map(id => <TouchableOpacity key={id} onPress={() => { setSection(id); setSelected(null); }} accessibilityRole="button" accessibilityLabel={`Open ${SECTION_LABELS[id]} Backpack section`} style={[styles.tab, { borderColor: section === id ? skin.accent : `${skin.border}80`, backgroundColor: section === id ? `${skin.accent}18` : `${skin.panel}CC` }]}><MaterialCommunityIcons name={ICONS[id] as any} size={14} color={section === id ? skin.accent : skin.mid} /><Text style={[styles.tabText, { color: section === id ? skin.accent : skin.mid }]}>{SECTION_LABELS[id]}</Text></TouchableOpacity>)}</ScrollView>
    <Text style={[styles.resultHint, { color: skin.mid }]}>{query.trim() ? `${items.length} matches in ${SECTION_LABELS[section]}` : `${items.length} items in ${SECTION_LABELS[section]} · tap any item for a reversible preview`}</Text>
    <View style={styles.grid}>{items.map(item => { const ready = unlocked(item); const active = item.section === 'styles' && typeof item.patch?.styleId === 'string' && STYLE_PRESETS.find(s => s.id === item.patch?.styleId)?.themeId === activePackId; return <TouchableOpacity key={item.id} disabled={false} onPress={() => { setSelected(item); if (item.section === 'styles') { const preset = STYLE_PRESETS.find(s => s.id === item.patch?.styleId); if (preset) startPreview(preset.themeId); } }} accessibilityRole="button" accessibilityLabel={`${item.label}, ${ready ? 'available' : 'locked'}`} style={[styles.item, { borderColor: active ? skin.ok : ready ? `${skin.accent}65` : `${skin.mid}35`, backgroundColor: active ? `${skin.ok}12` : `${skin.panel}CC`, opacity: ready ? 1 : 0.58 }]}><View style={styles.itemTop}><MaterialCommunityIcons name={item.section === 'graphs' ? 'chart-line' : item.section === 'styles' ? 'palette-swatch' : 'cube-outline'} size={18} color={active ? skin.ok : ready ? skin.accent : skin.mid} /><Text style={[styles.itemLabel, { color: skin.text }]} numberOfLines={1}>{item.label}</Text>{!ready && <MaterialCommunityIcons name="lock-outline" size={14} color={skin.warn} />}</View><Text style={[styles.itemDescription, { color: skin.mid }]} numberOfLines={2}>{item.description}</Text><Text style={[styles.itemNickname, { color: ready ? skin.accent2 : skin.mid }]} numberOfLines={1}>{nicknames[item.id] || 'NAMING…'}</Text><Text style={[styles.itemMeta, { color: ready ? skin.accent : skin.warn }]}>{ready ? item.performance.toUpperCase() : item.entitlement.toUpperCase()}</Text></TouchableOpacity>; })}</View>
    {selected && <View style={[styles.preview, { borderColor: skin.accent3, backgroundColor: `${skin.accent3}12` }]}><View style={{ flex: 1 }}><Text style={[styles.previewTitle, { color: skin.accent3 }]}>{selected.label}</Text><Text style={[styles.previewText, { color: skin.mid }]}>{selected.description}</Text></View>{selected.section === 'styles' && <TouchableOpacity accessibilityRole="button" accessibilityLabel={`Apply ${selected.label}`} disabled={!unlocked(selected)} onPress={() => applyStyle(selected)} style={[styles.apply, { borderColor: skin.ok, backgroundColor: `${skin.ok}18`, opacity: unlocked(selected) ? 1 : 0.45 }]}><Text style={[styles.applyText, { color: skin.ok }]}>APPLY</Text></TouchableOpacity>}</View>}
  </View>;
});

const styles = StyleSheet.create({ root: { borderWidth: 1, borderRadius: 14, padding: 10, gap: 9 }, search: { minHeight: 48, borderWidth: 1, borderRadius: 11, flexDirection: 'row', alignItems: 'center', gap: 7, paddingHorizontal: 10 }, searchInput: { flex: 1, minHeight: 44, fontFamily: 'monospace', fontSize: 10 }, resultHint: { fontFamily: 'monospace', fontSize: 7.5, lineHeight: 11 }, headingRow: { flexDirection: 'row', alignItems: 'center', gap: 9 }, backpackIcon: { width: 42, height: 42, borderWidth: 1.3, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, heading: { fontFamily: 'monospace', fontSize: 14, fontWeight: '900', letterSpacing: 1.3 }, sub: { fontFamily: 'monospace', fontSize: 7.5, letterSpacing: 0.5, marginTop: 3 }, count: { minWidth: 46, borderWidth: 1, borderRadius: 9, padding: 5, alignItems: 'center' }, countText: { fontFamily: 'monospace', fontSize: 16, fontWeight: '900' }, countLabel: { fontFamily: 'monospace', fontSize: 6.5 }, tabs: { gap: 5, paddingVertical: 1 }, tab: { flexDirection: 'row', alignItems: 'center', gap: 4, minHeight: 32, borderWidth: 1, borderRadius: 8, paddingHorizontal: 8 }, tabText: { fontFamily: 'monospace', fontSize: 7, fontWeight: '900' }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 }, item: { width: '48.8%', minHeight: 92, borderWidth: 1, borderRadius: 10, padding: 8, gap: 5 }, itemTop: { flexDirection: 'row', alignItems: 'center', gap: 5 }, itemLabel: { flex: 1, fontFamily: 'monospace', fontSize: 8, fontWeight: '900' }, itemDescription: { fontFamily: 'monospace', fontSize: 7, lineHeight: 10 }, itemNickname: { fontFamily: 'monospace', fontSize: 6.5, fontWeight: '900', letterSpacing: 0.7 }, itemMeta: { fontFamily: 'monospace', fontSize: 6.5, fontWeight: '900', letterSpacing: 0.8 }, preview: { flexDirection: 'row', alignItems: 'center', gap: 8, borderWidth: 1, borderRadius: 10, padding: 9 }, previewTitle: { fontFamily: 'monospace', fontSize: 9, fontWeight: '900' }, previewText: { fontFamily: 'monospace', fontSize: 7, lineHeight: 11, marginTop: 3 }, apply: { borderWidth: 1, borderRadius: 8, minWidth: 64, minHeight: 36, alignItems: 'center', justifyContent: 'center' }, applyText: { fontFamily: 'monospace', fontSize: 8, fontWeight: '900' } });

export default ButlerBackpackInventory;
