import React, { memo, useMemo } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import Svg, { Circle, G, Line, Path, Rect } from 'react-native-svg';
import { graphVariant } from '@/services/cosmeticVariantRegistry';
import { useSkin } from '@/hooks/useSkin';

export type ButlerGraphVariantRendererProps = { variantId: string; data?: readonly number[]; series?: readonly (readonly number[])[]; width?: number; height?: number; label?: string; offlineLabel?: string };
const clamp = (n: number, min: number, max: number) => Math.max(min, Math.min(max, n));
const pointsFor = (data: readonly number[], width: number, height: number, pad = 8) => { if (!data.length) return ''; const min = Math.min(...data); const max = Math.max(...data); const range = max - min || 1; return data.map((value, i) => `${i ? 'L' : 'M'}${pad + (i / Math.max(1, data.length - 1)) * (width - pad * 2)} ${height - pad - ((value - min) / range) * (height - pad * 2)}`).join(' '); };

export const ButlerGraphVariantRenderer = memo(function ButlerGraphVariantRenderer({ variantId, data = [], series = [], width = 300, height = 120, label, offlineLabel = 'NO SERVER DATA' }: ButlerGraphVariantRendererProps) {
  const skin = useSkin();
  const variant = graphVariant(variantId);
  const accent = variant?.props.palette === 'ember' ? '#FF4D5E' : skin.accent;
  const path = useMemo(() => pointsFor(data, width, height), [data, height, width]);
  if (!variant) return <View style={[styles.empty, { borderColor: `${skin.warn}55` }]}><Text style={[styles.emptyText, { color: skin.warn }]}>UNKNOWN GRAPH PRESET</Text></View>;
  if (!data.length && !series.length) return <View style={[styles.empty, { minHeight: height, borderColor: `${accent}45`, backgroundColor: `${skin.panel}CC` }]}><Text style={[styles.emptyLabel, { color: accent }]}>{variant.label.toUpperCase()}</Text><Text style={[styles.emptyText, { color: skin.mid }]}>{offlineLabel}</Text><Text style={[styles.emptyHint, { color: skin.mid }]}>PAIR THE LOCAL PC SERVER TO POPULATE THIS GRAPH</Text></View>;
  const family = variant.family;
  if (family === 'bar') { const values = data.length ? data : (series[0] ?? []); const max = Math.max(1, ...values); return <Svg width={width} height={height}><G>{values.map((v, i) => { const gap = 4; const bw = Math.max(4, (width - gap * (values.length + 1)) / Math.max(1, values.length)); const bh = clamp((Math.max(0, v) / max) * (height - 18), 2, height - 18); return <Rect key={i} x={gap + i * (bw + gap)} y={height - bh - 8} width={bw} height={bh} rx={variant.props.horizontal ? 2 : 4} fill={accent} opacity={0.58 + (i % 3) * 0.12} />; })}</G></Svg>; }
  if (family === 'radial' || family === 'gauge') { const value = clamp(data[0] ?? 0, 0, 100); const cx = width / 2; const cy = family === 'gauge' ? height - 10 : height / 2; const r = Math.min(width, height) * 0.32; const circumference = 2 * Math.PI * r; const dash = circumference * value / 100; return <Svg width={width} height={height}><Circle cx={cx} cy={cy} r={r} stroke={`${accent}22`} strokeWidth={variant.props.rings === 3 ? 9 : 12} fill="none" /><Circle cx={cx} cy={cy} r={r} stroke={accent} strokeWidth={variant.props.rings === 3 ? 9 : 12} fill="none" strokeDasharray={`${dash} ${circumference - dash}`} strokeLinecap="round" rotation={family === 'gauge' ? -180 : -90} origin={`${cx}, ${cy}`} /></Svg>; }
  if (family === 'heat') { const values = data; const cols = Math.min(12, Math.max(1, Math.ceil(Math.sqrt(values.length)))); const cell = Math.max(8, Math.floor((width - 16) / cols)); const max = Math.max(1, ...values); return <Svg width={width} height={height}><G>{values.map((v, i) => <Rect key={i} x={8 + (i % cols) * cell} y={8 + Math.floor(i / cols) * cell} width={cell - 3} height={cell - 3} rx={3} fill={accent} opacity={0.12 + (Math.max(0, v) / max) * 0.82} />)}</G></Svg>; }
  if (family === 'node-link') { const cx = width / 2; const cy = height / 2; const radius = Math.min(width, height) * 0.32; const count = Math.max(3, Math.min(8, data.length)); return <Svg width={width} height={height}><G>{Array.from({ length: count }, (_, i) => { const a = (i / count) * Math.PI * 2; const x = cx + Math.cos(a) * radius; const y = cy + Math.sin(a) * radius; return <G key={i}><Line x1={cx} y1={cy} x2={x} y2={y} stroke={`${accent}70`} strokeWidth={1} /><Circle cx={x} cy={y} r={4 + (Math.abs(data[i] ?? 0) % 4)} fill={accent} /><Circle cx={cx} cy={cy} r={6} fill={skin.panel} stroke={accent} strokeWidth={2} /></G>; })}</G></Svg>; }
  if (family === 'terminal' || family === 'timeline') return <View style={[styles.terminal, { minHeight: height, borderColor: `${accent}45`, backgroundColor: `${skin.panel}CC` }]}>{data.slice(0, 8).map((v, i) => <Text key={i} style={[styles.terminalLine, { color: i === data.slice(0, 8).length - 1 ? accent : skin.mid }]}>{family === 'terminal' ? `> ${label ?? 'telemetry'} ${String(v)}` : `● ${i + 1} · ${String(v)}`}</Text>)}</View>;
  const fill = family === 'area' ? `${accent}30` : 'none'; const areaPath = path ? `${path} L${width - 8} ${height - 8} L8 ${height - 8} Z` : '';
  return <Svg width={width} height={height}><Line x1={8} y1={height - 8} x2={width - 8} y2={height - 8} stroke={`${accent}28`} strokeWidth={1} />{fill !== 'none' && areaPath && <Path d={areaPath} fill={fill} />}{path && <Path d={path} fill="none" stroke={accent} strokeWidth={variant.props.glow ? 3 : 2} strokeLinecap="round" strokeLinejoin="round" />}{variant.props.marker && data.length > 0 && <Circle cx={width - 8} cy={height - 8 - ((data[data.length - 1] - Math.min(...data)) / (Math.max(...data) - Math.min(...data) || 1)) * (height - 16)} r={4} fill={accent} />}</Svg>;
});

const styles = StyleSheet.create({ empty: { borderWidth: 1, borderRadius: 10, padding: 12, alignItems: 'center', justifyContent: 'center', gap: 5 }, emptyLabel: { fontFamily: 'monospace', fontSize: 8, fontWeight: '900', letterSpacing: 1 }, emptyText: { fontFamily: 'monospace', fontSize: 9, fontWeight: '900' }, emptyHint: { fontFamily: 'monospace', fontSize: 7, textAlign: 'center' }, terminal: { borderWidth: 1, borderRadius: 10, padding: 10, justifyContent: 'center', gap: 5 }, terminalLine: { fontFamily: 'monospace', fontSize: 8 } });

export default ButlerGraphVariantRenderer;
