/**
 * SecurityShowcase — security carousel + 6-tile stat grid.
 *
 *   <SecurityShowcase mode="full"  />  // onboarding step 1 (hero)
 *   <SecurityShowcase mode="strip" />  // homepage one-line ticker
 */
import React, { useEffect, useRef, useState, useCallback } from 'react';
import { View, Text, TouchableOpacity, Platform, StyleSheet } from 'react-native';
import { MaterialIcons, MaterialCommunityIcons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { haptics } from '@/services/haptics';
// MicroGlyph removed — it statically imports react-native-svg which crashes Android boot.
// Replaced with pure View-based decorative marks (zero native dependencies).
function TinyMark({ size = 8, color = '#5A6880', style }: { size?: number; color?: string; style?: any }) {
  return (
    <View style={[{ width: size, height: size, borderRadius: 2, borderWidth: 1, borderColor: color, opacity: 0.55 }, style]}
      pointerEvents="none" />
  );
}
function CornerGlyph({ color, corner = 'tr', inset = 8 }: { color: string; corner?: 'tl'|'tr'|'bl'|'br'; inset?: number }) {
  const pos: any = { position: 'absolute' };
  if (corner.includes('t')) pos.top = inset; else pos.bottom = inset;
  if (corner.includes('r')) pos.right = inset; else pos.left = inset;
  return <TinyMark color={color} size={7} style={pos} />;
}
import { FootNote } from './MicroCopy';

const MONO: any = Platform.select({ ios: 'Menlo-Bold', default: 'monospace' });
const C = {
  card: '#070d1a', card2: '#09111f', border: '#0f1e30',
  cyan: '#00e5ff', green: '#00ff9d', amber: '#ffb020',
  purple: '#c85cff', blue: '#4d8dff', text: '#D7E4F2', dim: '#5A6880',
};

export interface SecurityFact {
  icon: string; mcIcon: string; color: string;
  label: string; detail: string; tab: string; route: string;
}

export const SECURITY_FACTS: SecurityFact[] = [
  { icon: 'lock', mcIcon: 'lock-outline',             color: C.cyan,   label: 'AES-256-GCM',      detail: 'All PC bridge traffic encrypted with AES-256-GCM. No plaintext ever crosses the LAN.',                         tab: 'settings', route: '/(tabs)/settings' },
  { icon: 'signal-wifi-off', mcIcon: 'wifi-off',      color: C.green,  label: 'LAN ONLY',         detail: 'Zero internet required. Butler never connects outside your local network. Verified by network firewall rules.', tab: 'settings', route: '/(tabs)/settings' },
  { icon: 'analytics', mcIcon: 'chart-line',          color: C.amber,  label: 'ZERO TELEMETRY',   detail: 'No analytics, no crash reports, no usage data. Nothing leaves your device or LAN — ever.',                     tab: 'settings', route: '/(tabs)/settings' },
  { icon: 'cloud-off', mcIcon: 'cloud-off-outline',   color: C.purple, label: 'NO CLOUD RELAY',   detail: 'Commands go phone → LAN → PC directly. No relay server, no middleman, no cloud dependency.',                  tab: 'settings', route: '/(tabs)/settings' },
  { icon: 'vpn-key',   mcIcon: 'key-variant',         color: C.blue,   label: '64C TOKEN',        detail: 'Session authenticated with a 64-character HMAC-SHA256 token generated at pairing time.',                       tab: 'settings', route: '/(tabs)/settings' },
  { icon: 'shield',    mcIcon: 'shield-key-outline',  color: C.green,  label: 'SHA-256 HMAC',     detail: 'Every API request signed with SHA-256 HMAC. Replay and injection attacks are rejected at the server.',          tab: 'settings', route: '/(tabs)/settings' },
  { icon: 'storage',   mcIcon: 'database-lock',       color: C.cyan,   label: 'LOCAL STORAGE',    detail: 'All app data in on-device encrypted AsyncStorage. No Supabase, no Firebase, no third-party DB.',               tab: 'knowledge', route: '/(tabs)/knowledge' },
  { icon: 'memory',    mcIcon: 'chip',                color: C.amber,  label: 'LOCAL AI MODEL',   detail: 'Ollama runs qwen2.5-coder:7b on your own PC. No OpenAI, no Anthropic, no tokens billed to you.',               tab: 'butler',   route: '/(tabs)/butler'   },
  { icon: 'qr-code',   mcIcon: 'qrcode-scan',         color: C.blue,   label: 'QR PAIRING',       detail: 'Pairing is one-scan with a QR code generated by butler_server.py. No account, no signup.',                     tab: 'nexushome', route: '/(tabs)/nexushome' },
  { icon: 'verified',  mcIcon: 'check-decagram',      color: C.green,  label: 'VERIFIED SECURE',  detail: 'Security posture verified on every app launch: token present, LAN-only mode active, HMAC auth working.',       tab: 'settings', route: '/(tabs)/settings' },
  { icon: 'code',      mcIcon: 'code-braces',         color: C.purple, label: '250+ SCRIPTS',     detail: 'Over 250 Python automation scripts, all executed locally on your PC — never sent to a cloud interpreter.',      tab: 'scripts',  route: '/(tabs)/scripts'  },
  { icon: 'folder',    mcIcon: 'folder-lock-outline', color: C.amber,  label: 'FILE VAULT',       detail: 'File transfer and clipboard sync use the same AES-256-GCM channel. Nothing is cached on the phone.',           tab: 'fileshare', route: '/(tabs)/fileshare' },
  { icon: 'bar-chart', mcIcon: 'chart-bar',           color: C.cyan,   label: 'INTEL LOGS',       detail: 'Execution logs stored on-device only. Purged after 90 days. Never uploaded or shared.',                        tab: 'logs',     route: '/(tabs)/logs'     },
  { icon: 'palette',   mcIcon: 'palette-swatch',      color: C.purple, label: 'COSMETIC ONLY',    detail: 'Cosmetic skins change colors and fonts only — never touch logic, permissions, or network config.',              tab: 'cosmetic', route: '/(tabs)/cosmetic' },
  { icon: 'handyman',  mcIcon: 'wrench-outline',      color: C.blue,   label: 'BUILDER SANDBOX',  detail: 'Automation Builder scripts run in an isolated Python subprocess. No shell escape, no root access.',             tab: 'builder',  route: '/(tabs)/builder'  },
  { icon: 'brain',     mcIcon: 'brain',               color: C.green,  label: 'SELF-LEARNING KB', detail: 'Knowledge base grows from local sessions only. No external data ingested without explicit user approval.',       tab: 'knowledge', route: '/(tabs)/knowledge' },
];

const STAT_TILES = [
  { Icon: MaterialIcons,          name: 'lock',                       big: 'AES-256', small: 'GCM ENCRYPT',  color: C.cyan },
  { Icon: MaterialIcons,          name: 'signal-wifi-off',            big: 'LAN',     small: 'ONLY MODE',    color: C.green },
  { Icon: MaterialIcons,          name: 'analytics',                  big: 'NO',      small: 'TELEMETRY',    color: C.amber },
  { Icon: MaterialIcons,          name: 'cloud-off',                  big: '0',       small: 'CLOUD RELAY',  color: C.purple },
  { Icon: MaterialIcons,          name: 'vpn-key',                    big: '64C',     small: 'TOKEN LENGTH', color: C.blue },
  { Icon: MaterialCommunityIcons, name: 'shield-key-outline',         big: 'SHA',     small: '256 HMAC',     color: C.green },
] as const;

export default function SecurityShowcase({ mode = 'full' }: { mode?: 'full' | 'strip' }) {
  const router = useRouter();
  const [idx, setIdx] = useState(0);
  const timer = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    timer.current = setInterval(
      () => setIdx(i => (i + 1) % Math.max(SECURITY_FACTS.length, 1)),
      4000,
    );
    return () => { if (timer.current) clearInterval(timer.current); };
  }, []);

  const fact = SECURITY_FACTS[idx] ?? SECURITY_FACTS[0];
  const open = useCallback(() => {
    haptics.selection();
    if (fact?.route) {
      try { router.push(fact.route as any); } catch {}
    }
  }, [fact, router]);

  if (!fact) return null;

  if (mode === 'strip') {
    return (
      <TouchableOpacity onPress={open} activeOpacity={0.8} style={s.strip}>
        <TinyMark size={9} color={fact.color} />
        <Text numberOfLines={1} style={[s.stripLabel, { color: fact.color }]}>{fact.label}</Text>
        <Text numberOfLines={1} style={s.stripDetail}>{fact.detail}</Text>
        <Text style={s.stripCount}>
          {String(idx + 1).padStart(2, '0')}/{SECURITY_FACTS.length}
        </Text>
      </TouchableOpacity>
    );
  }

  return (
    <View>
      {/* progress dots */}
      <View style={s.dotsRow}>
        <View style={{ flexDirection: 'row', gap: 4 }}>
          {SECURITY_FACTS.map((_, i) => (
            <View key={i} style={[s.dot, i === idx && { width: 14, backgroundColor: fact.color }]} />
          ))}
        </View>
        <View style={{ flexDirection: 'row', alignItems: 'center', gap: 4 }}>
          <Text style={s.tapText}>TAP FOR DETAILS</Text>
          <TinyMark size={8} color={C.dim} />
        </View>
      </View>

      {/* rotating fact card */}
      <TouchableOpacity onPress={open} activeOpacity={0.85}
        style={[s.factCard, { borderColor: fact.color + '55' }]}>
        <CornerGlyph color={fact.color} corner="tr" inset={7} />
        <View style={[s.factIcon, { borderColor: fact.color + '55' }]}>
          <MaterialCommunityIcons name={fact.mcIcon as any} size={20} color={fact.color} />
        </View>
        <View style={{ flex: 1 }}>
          <View style={{ flexDirection: 'row', alignItems: 'center', gap: 6 }}>
            <View style={[s.liveDot, { backgroundColor: fact.color }]} />
            <Text style={[s.factLabel, { color: fact.color }]}>{fact.label}</Text>
            <View style={s.verified}>
              <Text style={s.verifiedText}>✓ VERIFIED</Text>
            </View>
          </View>
          <Text numberOfLines={2} style={s.factDetail}>{fact.detail}</Text>
        </View>
        <View style={s.counter}>
          <Text style={s.counterBig}>{String(idx + 1).padStart(2, '0')}</Text>
          <Text style={s.counterSmall}>/{SECURITY_FACTS.length}</Text>
        </View>
      </TouchableOpacity>

      {/* 6-tile stat grid */}
      <View style={s.grid}>
        {STAT_TILES.map(t => (
          <View key={t.small} style={[s.tile, { borderColor: t.color + '45' }]}>
            <CornerGlyph color={t.color} corner="tr" inset={6} />
            <t.Icon name={t.name as any} size={18} color={t.color} />
            <Text style={[s.tileBig, { color: t.color }]}>{t.big}</Text>
            <Text style={s.tileSmall}>{t.small}</Text>
          </View>
        ))}
      </View>

      <FootNote>
        {`rotates every 4s · ${SECURITY_FACTS.length} verifiable guarantees · tap any card to jump to its source screen`}
      </FootNote>
    </View>
  );
}

const s = StyleSheet.create({
  strip: {
    height: 36, flexDirection: 'row', alignItems: 'center', gap: 8,
    paddingHorizontal: 12, borderRadius: 10, borderWidth: 1,
    borderColor: '#0f1e30', backgroundColor: '#070d1a',
  },
  stripLabel:  { fontFamily: MONO, fontSize: 9, letterSpacing: 1 },
  stripDetail: { fontFamily: MONO, fontSize: 8, color: '#5A6880', flex: 1 },
  stripCount:  { fontFamily: MONO, fontSize: 8, color: '#5A6880' },
  dotsRow: {
    flexDirection: 'row', justifyContent: 'space-between',
    alignItems: 'center', marginBottom: 8, paddingHorizontal: 2,
  },
  dot: { width: 5, height: 5, borderRadius: 3, backgroundColor: '#0f1e30' },
  tapText: { fontFamily: MONO, fontSize: 7, letterSpacing: 1, color: '#5A6880' },
  factCard: {
    flexDirection: 'row', alignItems: 'center', gap: 12, padding: 14,
    borderRadius: 14, borderWidth: 1, backgroundColor: '#070d1a',
  },
  factIcon: {
    width: 44, height: 44, borderRadius: 12, borderWidth: 1,
    alignItems: 'center', justifyContent: 'center',
    backgroundColor: '#09111f',
  },
  liveDot:   { width: 6, height: 6, borderRadius: 3 },
  factLabel: { fontFamily: MONO, fontSize: 13, letterSpacing: 1 },
  verified:  {
    borderWidth: 1, borderColor: '#0f1e30', borderRadius: 8,
    paddingHorizontal: 6, paddingVertical: 1,
  },
  verifiedText: { fontFamily: MONO, fontSize: 7, color: '#D7E4F2', letterSpacing: 1 },
  factDetail:   { fontFamily: MONO, fontSize: 9, color: '#5A6880', marginTop: 3, lineHeight: 13 },
  counter:      { alignItems: 'center' },
  counterBig:   { fontFamily: MONO, fontSize: 16, color: '#D7E4F2' },
  counterSmall: { fontFamily: MONO, fontSize: 8, color: '#5A6880' },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 10 },
  tile: {
    flexBasis: '30%', flexGrow: 1, alignItems: 'center', gap: 4,
    paddingVertical: 14, borderRadius: 14, borderWidth: 1,
    backgroundColor: '#070d1a',
  },
  tileBig:   { fontFamily: MONO, fontSize: 16, letterSpacing: 1 },
  tileSmall: { fontFamily: MONO, fontSize: 7.5, color: '#5A6880', letterSpacing: 1 },
});
